version: '3.4'

services:
  serverudp:
    # image: developer_university:latest # ${DOCKER_REGISTRY-}serverudp
    image: innovadeveloper/udp_server_university:latest
    # build:
    #   context: .
    #   dockerfile: ./ServerUDP/Dockerfile
    expose:
      - '27000/udp'
    ports:
      - '27000:27000/tcp'
      - '27000:27000/udp'
